# Generated by Django 4.2.1 on 2023-08-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mainpagestatic_plantedtrees_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagestatic',
            name='img',
            field=models.ImageField(default=2, upload_to='statistics/img/'),
            preserve_default=False,
        ),
    ]
