# Generated by Django 4.2.1 on 2023-08-13 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_abouttrees'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttrees',
            name='flowers',
            field=models.CharField(default=django.utils.timezone.now, max_length=1500),
            preserve_default=False,
        ),
    ]
