# Generated by Django 4.2.1 on 2023-08-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_abouttrees_flowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttrees',
            name='averageLifeTime',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abouttrees',
            name='bio',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abouttrees',
            name='cleanCO2Day',
            field=models.CharField(default=43, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abouttrees',
            name='cleanCO2Period',
            field=models.CharField(default=432, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abouttrees',
            name='cleanCO2Year',
            field=models.CharField(default=3421, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abouttrees',
            name='leaveSize',
            field=models.CharField(default=43, max_length=100),
            preserve_default=False,
        ),
    ]
