# Generated by Django 4.2.1 on 2023-08-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_abouttrees_averagelifetime_abouttrees_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttrees',
            name='additionBio',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
