# Generated by Django 4.2.1 on 2023-08-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_abouttrees_additionbio'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttrees',
            name='regionImage',
            field=models.ImageField(default=123, upload_to='regionImage/'),
            preserve_default=False,
        ),
    ]
