# Generated by Django 4.2.1 on 2023-08-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_abouttrees_regionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttrees',
            name='image1',
            field=models.ImageField(default=12, upload_to='trees/img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abouttrees',
            name='image2',
            field=models.ImageField(default=121, upload_to='trees/img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abouttrees',
            name='image3',
            field=models.ImageField(default=1213, upload_to='trees/img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abouttrees',
            name='image4',
            field=models.ImageField(default=1323, upload_to='trees/img/'),
            preserve_default=False,
        ),
    ]
