# Generated by Django 4.2.1 on 2023-08-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_abouttrees_image1_abouttrees_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTreesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
