# Generated by Django 4.2.1 on 2023-08-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_abouttrees_updated_at_alltreescount_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companieslist',
            name='companyWebSite',
            field=models.CharField(default=123, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companieslist',
            name='email',
            field=models.EmailField(default=312, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companieslist',
            name='password',
            field=models.CharField(default=2131, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companieslist',
            name='yourFullName',
            field=models.CharField(default=21213, max_length=200),
            preserve_default=False,
        ),
    ]
